services:
  backend:
    environment:
      - PORT=4000
    build: ./server
    expose:
      -  '4000'

  frontend:
    build: ./client
    ports:
      - '3000:80'
    # stdin_open: true
    # tty: true
    depends_on:
      - backend
    restart: on-failure
